language: generic
os:
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: qyyo8EvEpXIm/OC9Pq2GXP8gbN/DaWGnXu6ZBT6svLdmYwsWfyRRdPsb6RqT+QtaHd9qPNmtph9e+YmbMCNqim74tX4BeDDUzUkaG+j9rJjzxk9vkeIYGkJZd6ZiQaX8s9hk4NSaHmeL67XBvMQs21QrUGZh8KT1uBPQG8jPKX8Z0JkEMm1uImkXdoC6LijNr9Vogb/UAl5PmrzbYND0gn8gdN1tVdxKCV8VDPDiWqP3LYE0r46sq41eULHoKAc2hNCMCEMPuCEg7wLw1u3YgX/cnPktygMIcQAGCYeX+ojqivk92W0x+QZiOe37xXMUQcINeLO1q0nbcPxZeImGckiRiKnxAW3Aj3afyf91KRT1ENG2vHK21yQ1urhv93Bne0sMT2upr8+e1xmnog2K+87KC22F4Upj755H8fEQq7iUnmggMZteB6NF+lxWjLbdgLBcFdW8vGpaDJFsO3SjWmwlNIbnqgvElIVC9gCcLe+s7vUR/GNdCjLAi7Qi1W1UzpDjk9BjPW8f+Tk+FtJfFfckK8cD4laP1yg3MNOqiF5JeTFC9+MUetJeM4gX/QL/kFA2BlRoLcHnwNWl4mxhLvXfGk46WDXzq5JvMNjCTLmS6ud2t0Gpm/GTqMstIVSqqvmPDNoz8P5QNSThigpvSRj48bL04nEK9qUiaH0/l18=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
